import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');

const gb2312Raw = fs.readFileSync(path.join(rootDir, 'gb2312.txt'), 'utf8');
const gbkRaw = fs.readFileSync(path.join(rootDir, 'gbk.txt'), 'utf8');

const gb2312Chars = [...new Set([...gb2312Raw].filter(c => {
  const cp = c.codePointAt(0);
  return (cp >= 0x4E00 && cp <= 0x9FFF) || (cp >= 0x3400 && cp <= 0x4DBF);
}))];
const gbkChars = [...new Set([...gbkRaw].filter(c => {
  const cp = c.codePointAt(0);
  return (cp >= 0x4E00 && cp <= 0x9FFF) || (cp >= 0x3400 && cp <= 0x4DBF);
}))];

const gb2312Set = new Set(gb2312Chars);
const gbkSet = new Set(gbkChars);

console.log(`GB2312: ${gb2312Chars.length} chars`);
console.log(`GBK: ${gbkChars.length} chars`);

const charFreqPath = path.join(rootDir, 'src', 'data', 'charFrequency.ts');
const freqContent = fs.readFileSync(charFreqPath, 'utf8');

const orderMatch = freqContent.match(/export const charFreqOrder: string\[\] = \[([\s\S]*?)\];/);
if (!orderMatch) {
  console.error('Failed to parse charFreqOrder from charFrequency.ts');
  process.exit(1);
}

const charFreqOrder = orderMatch[1]
  .split(',')
  .map(s => s.trim().replace(/^'|'$/g, ''))
  .filter(s => s.length === 1);

console.log(`charFreqOrder: ${charFreqOrder.length} chars`);

const freqOrderedGB2312 = charFreqOrder.filter(c => gb2312Set.has(c));
const freqOrderedGBK = charFreqOrder.filter(c => gbkSet.has(c));

console.log(`Freq-ordered GB2312 chars: ${freqOrderedGB2312.length}`);
console.log(`Freq-ordered GBK chars: ${freqOrderedGBK.length}`);

const tongguiLevel1 = [];
for (const ch of freqOrderedGB2312) {
  if (tongguiLevel1.length >= 3500) break;
  tongguiLevel1.push(ch);
}

if (tongguiLevel1.length < 3500) {
  const usedSet = new Set(tongguiLevel1);
  for (const ch of gb2312Chars) {
    if (tongguiLevel1.length >= 3500) break;
    if (!usedSet.has(ch)) {
      tongguiLevel1.push(ch);
    }
  }
}

const tongguiLevel1And2 = [];
for (const ch of freqOrderedGBK) {
  if (tongguiLevel1And2.length >= 6500) break;
  tongguiLevel1And2.push(ch);
}

if (tongguiLevel1And2.length < 6500) {
  const usedSet = new Set(tongguiLevel1And2);
  const remaining = gbkChars.filter(c => !usedSet.has(c));
  remaining.sort((a, b) => a.codePointAt(0) - b.codePointAt(0));
  for (const ch of remaining) {
    if (tongguiLevel1And2.length >= 6500) break;
    tongguiLevel1And2.push(ch);
  }
}

const tongguiLevel2Set = new Set(tongguiLevel1And2);
const tongguiLevel1Set = new Set(tongguiLevel1);
const tongguiLevel2 = tongguiLevel1And2.filter(c => !tongguiLevel1Set.has(c));

const tongguiAll = [];
for (const ch of freqOrderedGBK) {
  tongguiAll.push(ch);
}

if (tongguiAll.length < 8105) {
  const usedSet = new Set(tongguiAll);
  const remaining = gbkChars.filter(c => !usedSet.has(c));
  remaining.sort((a, b) => a.codePointAt(0) - b.codePointAt(0));
  for (const ch of remaining) {
    if (tongguiAll.length >= 8105) break;
    tongguiAll.push(ch);
  }
}

if (tongguiAll.length > 8105) {
  tongguiAll.length = 8105;
}

console.log(`\nResults:`);
console.log(`  tongguiLevel1: ${tongguiLevel1.length} (expected 3500)`);
console.log(`  tongguiLevel2: ${tongguiLevel2.length} (expected 3000)`);
console.log(`  tongguiLevel1And2: ${tongguiLevel1And2.length} (expected 6500)`);
console.log(`  tongguiAll: ${tongguiAll.length} (expected 8105)`);

const level1Unique = new Set(tongguiLevel1);
const level2Unique = new Set(tongguiLevel2);
if (level1Unique.size !== tongguiLevel1.length) {
  console.warn(`  WARNING: tongguiLevel1 has duplicates! ${tongguiLevel1.length - level1Unique.size}`);
}
if (level2Unique.size !== tongguiLevel2.length) {
  console.warn(`  WARNING: tongguiLevel2 has duplicates! ${tongguiLevel2.length - level2Unique.size}`);
}

const overlap = tongguiLevel1.filter(c => level2Unique.has(c));
if (overlap.length > 0) {
  console.warn(`  WARNING: Level1 and Level2 overlap by ${overlap.length} chars`);
}

function formatArray(chars, indent = '  ') {
  const lines = [];
  for (let i = 0; i < chars.length; i += 20) {
    const chunk = chars.slice(i, i + 20);
    lines.push(indent + "'" + chunk.join("', '") + "'");
  }
  return lines.join(',\n');
}

const output = `// Auto-generated by scripts/gen-tonggui.mjs
// DO NOT EDIT MANUALLY
//
// 通用规范汉字表（近似字集）
//
// 数据来源：基于 charFrequency.ts 的字频排序 + GB2312/GBK 国标字集
// 构建方法：
//   - 通规一级(3500字)：从 charFreqOrder 中取前 3500 个在 GB2312 中的字
//   - 通规一二级(6500字)：从 charFreqOrder 中取前 6500 个在 GBK 中的字
//   - 通规全部(8105字)：从 charFreqOrder 中取前 8105 个在 GBK 中的字，不足则从 GBK 剩余字中按 Unicode 码点补充
//
// 注意：此为近似方案，非精确的《通用规范汉字表》官方数据
// 通规一级: ${tongguiLevel1.length} 字
// 通规二级: ${tongguiLevel2.length} 字
// 通规一二级: ${tongguiLevel1And2.length} 字
// 通规全部: ${tongguiAll.length} 字

export const tongguiLevel1: string[] = [
${formatArray(tongguiLevel1)}
];

export const tongguiLevel2: string[] = [
${formatArray(tongguiLevel2)}
];

export const tongguiLevel1And2: string[] = [
${formatArray(tongguiLevel1And2)}
];

export const tongguiAll: string[] = [
${formatArray(tongguiAll)}
];
`;

const outPath = path.join(rootDir, 'src', 'data', 'tongguiChars.ts');
fs.writeFileSync(outPath, output, 'utf8');
console.log(`\nWritten to ${outPath}`);
console.log(`File size: ${(Buffer.byteLength(output, 'utf8') / 1024).toFixed(1)} KB`);
